name: Android CI

on:
  push:
    paths:
      - '.github/workflows/android.yml'
      - 'TMessagesProj/**'
      - 'TMessagesProj_App/**'
      - 'TMessagesProj_AppHockeyApp/**'
      - 'TMessagesProj_AppHuawei/**'
      - 'TMessagesProj_AppStandalone/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'settings.gradle'
    branches-ignore:
      - 'wip/**'
  workflow_dispatch:

jobs:
  build:
    name: Build APKs
    runs-on: ${{ vars.IS_USING_HOSTED_RUNNERS == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Release APK
        env:
          SKETCHUB_API_KEY: ${{ secrets.SKETCHUB_API_KEY }}
        run: gradle assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: TMessagesProj/build/outputs/apk/release
      
