name: Android Docker Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: docker build -t android-builder .
      
    - name: Run Docker container
      run: |
        docker run \
          --name android-build \
          -v ${{ github.workspace }}:/home/source \
          android-builder
        
    - name: Save artifacts
      if: ${{ always() }}
      run: |
        mkdir -p artifacts
        cp -R ${{ github.workspace }}/TMessagesProj/build/outputs/ artifacts/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-build-outputs
        path: artifacts/
        if-no-files-found: error
