name: Android Docker Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Buildah
      uses: redhat-actions/buildah-setup@v1
      with:
        version: latest
        
    - name: Build image
      run: |
        buildah bud -t android-builder .
        
    - name: Create container
      run: |
        container=$(buildah from android-builder)
        buildah copy $container ${{ github.workspace }} /home/source
        
    - name: Run build commands
      run: |
        buildah run $container sh -c "mkdir -p /home/source/TMessagesProj/build/outputs/apk"
        buildah run $container sh -c "cd /home/gradle && gradle :TMessagesProj_App:assembleAfatRelease"
        
    - name: Extract artifacts
      run: |
        buildah unshare --mount sh -c "cp -r \$(buildah mount $container)/home/source/TMessagesProj/build/outputs artifacts"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-build-outputs
        path: artifacts/
