name: Android Docker CI

on:
 workflow_dispatch:
 push:
  branches: [ main ]
 pull_request:
  branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub (optional)
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Build Docker image
      run: docker build -t android-builder .
      
    - name: Run build in container
      run: |
        docker run --rm \
          -v "$(pwd):/home/source" \
          android-builder
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: apk-output
        path: |
          TMessagesProj/build/outputs/apk/
          TMessagesProj/build/outputs/bundle/
          TMessagesProj/build/outputs/native-debug-symbols/
