name: Docker Build (Manual)

on:
  workflow_dispatch:
    inputs:
      build-args:
        description: 'Additional Docker build args (optional)'
        required: false
        default: ''
      target:
        description: 'Docker build target (optional)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub (optional)
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
    - name: Build Docker image
      run: |
        docker build \
          --tag android-builder \
          ${{ github.event.inputs.build-args && '--build-arg ' + github.event.inputs.build-args || '' }} \
          ${{ github.event.inputs.target && '--target ' + github.event.inputs.target || '' }} \
          .
      
    - name: Run container and build Android project
      run: |
        docker run --rm \
          -v "$(pwd):/home/source" \
          android-builder
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-build-outputs
        path: |
          TMessagesProj/build/outputs/apk/
          TMessagesProj/build/outputs/bundle/
          TMessagesProj/build/outputs/native-debug-symbols/
